classdef Perch
    methods(Static)
        function x = FiltLick(x, Fs)
            % Isolate licking signal
            D = designfilt('lowpassiir', ...
                'FilterOrder', 10, ...
                'PassbandFrequency', 100, ...
                'StopbandAttenuation', 60, ...
                'PassbandRipple', 0.1, ...
                'DesignMethod','ellip', ...
                'SampleRate', Fs);
            
            dtype = class(x);
            x = filtfilt(D, double(x));
            x = cast(x, dtype);
        end
        
        function x = FiltMovement(x, Fs)
            % Isolate body movements
            D = designfilt('lowpassiir', ...
                'FilterOrder', 10, ...
                'PassbandFrequency', 50, ...
                'StopbandAttenuation', 80, ...
                'PassbandRipple', 0.1, ...
                'DesignMethod','ellip', ...
                'SampleRate', Fs);
            
            dtype = class(x);
            x = filtfilt(D, double(x));
            x = cast(x, dtype);
        end
        
        function x = FiltVibration(x, Fs)
            % Isolate lickport vibration
            D = designfilt('highpassiir', ...
                'FilterOrder', 10, ...
                'PassbandFrequency', 150, ...
                'StopbandAttenuation', 80, ...
                'PassbandRipple', 0.1, ...
                'DesignMethod','ellip', ...
                'SampleRate', Fs);
            
            dtype = class(x);
            x = filtfilt(D, double(x));
            x = cast(x, dtype);
        end
        
        function N = Volt2Newton(V)
            % Convert voltage value (Volt) of lickport Perch to lick force (Newton)
            N = V * SL.Param.gPerVolt / 1e3 * 9.8;
        end
    end
end